services:
  api:
    build:
      context: .
      dockerfile: YoutubeDownloader/Dockerfile
    container_name: yt-api
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: YoutubeDownloader.Web/Dockerfile
    container_name: yt-web
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - api
