FROM node:22-alpine AS build
WORKDIR /app

COPY YoutubeDownloader.Web/package*.json ./
RUN npm ci

COPY YoutubeDownloader.Web/ ./
RUN npm run build

FROM nginx:alpine AS runtime
COPY --from=build /app/dist /usr/share/nginx/html
COPY YoutubeDownloader.Web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
